### ISSUE TITLE
功能增强

### ISSUE THREAD

**Issue by itkld** [luoxiaojun1992/yii2-zipkin#3]
hi，我基于你的版本修正了bug,、添加了hprose rpc， 如果可以请合并到你的分支上。
https://github.com/itkld/yii2-zipkin

**Comment by luoxiaojun1992** [comment]
你好，请把bug修复部分单独提一个PR，方便code review后合并。这个项目的主要目的是把zipkin和yii进行集成，guzzle是广泛使用的http client，因此集成了http client。hprose rpc并不是通用的需求，建议可以单独创建一个项目，依赖本项目。谢谢。

**Comment by luoxiaojun1992** [comment]
详见 #4
